/**
 * Standardized Error Codes enum matching the API Contract.
 */
export const ErrorCodes = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NO_TOKEN: "NO_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  SESSION_REVOKED: "SESSION_REVOKED",
  CSRF_INVALID: "CSRF_INVALID",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  LINK_NOT_FOUND: "LINK_NOT_FOUND",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",
  RESERVED_USERNAME: "RESERVED_USERNAME",
  LINK_LIMIT_REACHED: "LINK_LIMIT_REACHED",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});
