/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#f9f9ff",
        "surface-dim": "#0b0e14",
        "surface-variant": "#202631",
        "on-tertiary": "#006257",
        "primary-dim": "#8a95ff",
        "surface": "#0b0e14",
        "primary-container": "#818cf8",
        "surface-container": "#151a22",
        "on-tertiary-fixed": "#00443c",
        "inverse-primary": "#4954bc",
        "surface-container-lowest": "#000000",
        "error": "#fd6f85",
        "outline": "#707583",
        "on-error-container": "#ff97a3",
        "primary-fixed": "#b6bcff",
        "secondary-dim": "#be83fa",
        "on-primary-fixed-variant": "#2e38a1",
        "tertiary-dim": "#48e5d0",
        "on-surface": "#e0e5f5",
        "secondary": "#ddb8ff",
        "surface-container-high": "#1b202a",
        "surface-container-low": "#10131b",
        "tertiary": "#8affec",
        "on-tertiary-fixed-variant": "#006358",
        "on-secondary-container": "#c489ff",
        "background": "#0b0e14",
        "secondary-fixed": "#f0dbff",
        "on-secondary-fixed-variant": "#783db1",
        "primary": "#919bff",
        "on-primary-fixed": "#041085",
        "outline-variant": "#424855",
        "surface-bright": "#262c39",
        "on-tertiary-container": "#00594f",
        "tertiary-fixed-dim": "#48e5d0",
        "tertiary-fixed": "#5bf4de",
        "error-dim": "#c8475d",
        "on-background": "#e0e5f5",
        "on-primary-container": "#00055a",
        "tertiary-container": "#5bf4de",
        "secondary-fixed-dim": "#e6c9ff",
        "surface-container-highest": "#202631",
        "inverse-on-surface": "#52555c",
        "secondary-container": "#3a0068",
        "on-secondary": "#5b1c94",
        "error-container": "#8a1632",
        "primary-fixed-dim": "#a5adff",
        "on-error": "#490013",
        "on-primary": "#000b83",
        "on-secondary-fixed": "#5a1a93",
        "on-surface-variant": "#a5abba",
        "surface-tint": "#919bff"
      },
      borderRadius: {
        "xl": "1.5rem",
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}