export const PLATFORM_METADATA = Object.freeze({
  youtube: {
    name: "YouTube",
    badge: "YT",
    color: "#ff0000",
    label: "SUBSCRIBERS",
    description: "Import channel metrics, subscribers, and profile signals.",
    placeholder: "Channel handle e.g. @mkbhd or URL",
  },
  github: {
    name: "GitHub",
    badge: "GH",
    color: "#c6f035",
    label: "FOLLOWERS",
    description: "Sync repositories, public activity, and developer follower graph.",
    placeholder: "GitHub username e.g. torvalds",
  },
  instagram: {
    name: "Instagram",
    badge: "IG",
    color: "#d946ef",
    label: "FOLLOWERS",
    description: "Display live follower counts and visual profile signals.",
    placeholder: "Instagram handle e.g. instagram",
  },
  tiktok: {
    name: "TikTok",
    badge: "TK",
    color: "#00f2ff",
    label: "FOLLOWERS",
    description: "Aggregate TikTok community reach and creator signals.",
    placeholder: "TikTok handle e.g. @tiktok",
  },
  twitter: {
    name: "X (Twitter)",
    badge: "X",
    color: "#e2e8f0",
    label: "FOLLOWERS",
    description: "Connect your public microblog handle and network reach.",
    placeholder: "Handle e.g. @elonmusk",
  },
  linkedin: {
    name: "LinkedIn",
    badge: "IN",
    color: "#0a66c2",
    label: "CONNECTIONS",
    description: "Surface your professional profile and industry network.",
    placeholder: "Profile username or URL",
  },
  spotify: {
    name: "Spotify",
    badge: "SP",
    color: "#1db954",
    label: "LISTENERS",
    description: "Feature artist profile, monthly listeners, and top tracks.",
    placeholder: "Artist name or Spotify URL",
  },
  telegram: {
    name: "Telegram",
    badge: "TG",
    color: "#229ed9",
    label: "SUBSCRIBERS",
    description: "Connect Telegram channel or group to stream live subscriber metrics.",
    placeholder: "Channel handle e.g. @telegram or t.me/channel",
  },
});
